In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [32]:
train=pd.read_csv('updated_train.csv')

In [33]:
train=train.fillna(0)

In [34]:
lenr=[]
for i in range(train.shape[0]):
    if train.loc[i,'Body']!=0:
        print(train.loc[i,'Body'])
        lenr.append(len(train.loc[i,'Body']))

**Central thread for sharing coronavirus News and discussion. Any off topic comments will be removed.**

#####Indian Goverment
* [Official Twitter Collection of Indian Govt. Communications](https://twitter.com/i/events/1240662046280048646)
* [State and District Wise Details of Cases in India](https://www.mohfw.gov.in/pdf/DistrictWiseList324.pdf)
* All India Helplines: 1075 (Toll Free) | 1930 (Toll Free) | 1944 (Northeast India Only) | +911123978046 | Email ID: ncov2019@gov.in 
* [State Helpline Numbers](https://www.mohfw.gov.in/pdf/coronvavirushelplinenumber.pdf)
* [Test Centers List](https://covid.icmr.org.in/index.php/testing-facilities)

#####State Specific Threads via Reddit community
* [Andaman &amp; Nicobar, Lakshadweep,  Puducherry, Dadra &amp; Nagar Haveli, Daman &amp; Diu](https://www.reddit.com/r/CoronaIndia/comments/fqmry7/coronavirus_covid19_megathread_news_and_updates/) via u/TheDosaMan
* [Bihar](https://www.reddit.com/r/india/comments/ftky3g/covid19_every_updates_from_bih

In [35]:
lenr

[9192,
 1002,
 1505,
 801,
 1357,
 465,
 623,
 2490,
 630,
 3212,
 128,
 1077,
 158,
 650,
 897,
 1777,
 613,
 176,
 628,
 417,
 1149,
 605,
 836,
 958,
 1092,
 6782,
 710,
 1088,
 1454,
 110,
 1229,
 249,
 722,
 121,
 2477,
 1792,
 1230,
 331,
 3865,
 309,
 282,
 281,
 58,
 3182,
 464,
 358,
 217,
 300,
 261,
 305,
 890,
 187,
 919,
 722,
 2780,
 486,
 551,
 1005,
 271,
 696,
 937,
 752,
 622,
 503,
 340,
 484,
 578,
 285,
 1853,
 254,
 115,
 1347,
 602,
 471,
 1519,
 387,
 2511,
 3665,
 2273,
 432,
 2348,
 309,
 3813,
 915,
 147,
 1383,
 260,
 145,
 1370,
 1812,
 695,
 155,
 2537,
 410,
 276,
 139,
 1007,
 350,
 142,
 173,
 317,
 1716,
 773,
 558,
 1049,
 6196,
 188,
 293,
 387,
 1121,
 174,
 809,
 1265,
 179,
 3065,
 1665,
 495,
 266,
 191,
 1374,
 1722,
 516,
 281,
 416,
 5203,
 1806,
 335,
 14750,
 1300,
 143,
 269,
 375,
 707,
 1104,
 3014,
 684,
 4173,
 198,
 391,
 7113,
 243,
 539,
 201,
 932,
 337,
 773,
 2838,
 314,
 471,
 4063,
 507,
 186,
 5149,
 2596,
 245,
 604,
 666,
 10

In [36]:
a=train.loc[1,'Body']

In [37]:
train['Num_Comments'].group_by(train['Label1Coronovirus']==1)

AttributeError: 'Series' object has no attribute 'group_by'

In [38]:
train

Unnamed: 0  Unnamed: 0.1  idx  \
0             0             0    0   
1             1             1    1   
2             2             2    2   
3             3             3    3   
4             4             4    4   
5             5             5    5   
6             6             6    6   
7             7             7    7   
8             8             8    8   
9            10            10   10   
10           11            11   11   
11           12            12   12   
12           13            13   13   
13           14            14   14   
14           15            15   15   
15           17            17   17   
16           19            19   19   
17           20            20   20   
18           21            21   21   
19           23            23   23   
20           24            24   24   
21           25            25   25   
22           26            26   26   
23           27            27   27   
24           28            28   28   
25           29            29   29   
26           30            30   30   
27           31            31   31   
28           32            32   32   
29           33            33   33   
..          ...           ...  ...   
443         473           635  635   
444         474           636  636   
445         475           643  643   
446         476           644  644   
447         477           645  645   
448         478           647  647   
449         479           648  648   
450         480           650  650   
451         481           652  652   
452         482           655  655   
453         483           656  656   
454         485           659  659   
455         486           661  661   
456         487           662  662   
457         488           663  663   
458         489           664  664   
459         490           666  666   
460         491           667  667   
461         492           669  669   
462         493           670  670   
463         494           671  671   
464         495           672  672   
465         496           675  675   
466         499           682  682   
467         500           684  684   
468         501           685  685   
469         502           686  686   
470         503           688  688   
471         504           690  690   
472         505           691  691   

                                                 Title  Score      ID  \
0    Coronavirus (COVID-19) Megathread - News and U...    287  fqqdsg   
1    Firozabad police fact-checking zee news (trans...    680  fwcz7h   
2    Donald Trump talks of ‘retaliation’ if India t...    371  fwclvi   
3    Mom came up with this impressive idea to celeb...   3129  fvz69t   
4    9 PM 9 Minutes: House Catches Fire In Bihar; G...    181  fwdysc   
5                               Cartoon by Pencilashan    120  fwep0p   
6    Pandemic impact: Mukesh Ambani's net worth dro...    138  fwd6mm   
7                               Symbiotic Relationship   1008  fw163b   
8    Coronavirus: How Shashi Tharoor Spent His MP F...    116  fwcvid   
9    Raipur AIIMS denies 'spitting, misbehaviour' b...     93  fwdn4o   
10   ICMR prepares plan to increase testing capacit...     88  fwdpr5   
11   Viral audio: False conspiracy theory about Mod...     65  fweoev   
12   Explained: Sampling bias drove sensationalist ...     70  fwe3n9   
13   Kerala Develops India's First Walk-In Kiosk Fo...    561  fw1uyw   
14   Coronavirus & Hydroxychloroquine -- India Cuts...     80  fwcud7   
15   No ration cards, no food supplies. Hunger stal...     53  fwe8vk   
16   Jamia Professor, Suspended For 'Failing 15 Non...     41  fwewf8   
17   Over 1,000 Attend Tribal Procession In Rajasth...     46  fwdoe5   
18   Medicines run dry as coronavirus lockdown hits...     52  fwc7o6   
19   Covid-19 lockdown impact: Unemployment rate ri...     28  fweqm5   
20   Inspired By South Korea, Walk-In COVID-19 Test...     25  fwf1hn   
21   Stones Thrown At Karnataka Cops For S

In [39]:
train.groupby('Label1Coronovirus',as_index=False)['Num_Comments'].mean()

Label1Coronovirus  Num_Comments
0                  0     17.569405
1                  1     70.050000

In [40]:
train.groupby('Label2Politics',as_index=False)['Num_Comments'].mean()

Label2Politics  Num_Comments
0               0     33.643646
1               1     21.882883

In [41]:
train.groupby('Label3Non-Political',as_index=False)['Num_Comments'].mean()

Label3Non-Political  Num_Comments
0                    0     33.733509
1                    1     19.393617

In [324]:
train.groupby('Label4Objects',as_index=False)['Num_Comments'].mean()

Label4Objects  Num_Comments
0              0     34.066339
1              1     11.257576

In [325]:
train.groupby('Label5AskIndia',as_index=False)['Num_Comments'].mean()

Label5AskIndia  Num_Comments
0               0     34.273657
1               1     14.719512

In [42]:
title_sents=[]
for i in range(train.shape[0]):
    title_sents.append(train.loc[i,'Title'])
    
        
#title_sents

In [43]:
import torch
import torch.nn as nn
import torch.optim as optim

#pip install torchtext
import torchtext

import spacy

In [44]:
import string
k=string.punctuation

punct=[]
for i in range(len(k)):
    if(k[i]=='?'):
        continue
    else: 
        punct.append(k[i])
    


In [45]:
spacy_eng=spacy.load('en')
nlp=spacy.load("en_core_web_sm")
def tokenize_eng(text):
    sent=[]
    lema=nlp(text)
    for tok in spacy_eng.tokenizer(text):
        
        word=tok.lemma_
        #word=tok.text
        
        if word not in punct:
            if word not in stop:
                sent.append(word)
    
    return sent

In [48]:

for sent in title_sents:
    sent=tokenize_eng(sent)
    print(sent)
    break

['Coronavirus', 'COVID-19', 'Megathread', 'News', 'Updates', '3']


In [49]:
title_sents[0]

'Coronavirus (COVID-19) Megathread - News and Updates - 3'

In [50]:
tokenize_eng(title_sents[0])

['Coronavirus', 'COVID-19', 'Megathread', 'News', 'Updates', '3']

In [21]:
a="Hello my name is Ishan what about you what is your name"
tokenize_eng(a)

['Hello', 'name', 'Ishan', 'name']

In [47]:
import nltk
from nltk.corpus import stopwords
stop=set(stopwords.words('english'))

In [23]:
if 'a' in stop:
    print("He;;")

He;;


In [24]:
train.to_csv('up')

In [51]:
from torchtext.data import Field


TEXT=Field(sequential=True,tokenize=tokenize_eng,lower=True,batch_first=True)
LABEL=Field(sequential=False,use_vocab=False,batch_first=True)
#NUM=Field(sequential=True,use_vocab=False,tokenize=toke,batch_first=True)

In [52]:

from torchtext.data import TabularDataset

flair_fields=[('Unnamed:0',None),
        ('Unnamed: 0.1',None),
        ('idx',None),
         ('Title',TEXT),
         ('Score',None),
         ('ID',None),
         ('Image',None),
         ('Num_Comments',None),
         ('Created',None),
         ('Body',TEXT),
         ('Label1Coronovirus',LABEL),
         ('Label2Politics',LABEL),
         ('Label3Non-Political',LABEL),
         ('Label4Objects',LABEL),
         ('Label5AskIndia',LABEL)]
         

In [53]:
train_data_csv=TabularDataset(path='updated_train.csv',
                    format='csv',
                    skip_header=True,
                    fields=flair_fields)

In [54]:
train_data_csv[13].Title,train_data_csv[3].Label1Coronovirus,train_data_csv[3].Body


(['kerala',
  'develops',
  'india',
  'first',
  'walk',
  'in',
  'kiosk',
  'for',
  'coronavirus',
  'test',
  'covid-19',
  'india'],
 '0',
 [])

In [29]:
if train_data_csv[3].Body==[1,]:
    print("hello")

In [55]:
TEXT.build_vocab(train_data_csv,min_freq=1,vectors='fasttext.simple.300d')

In [140]:
from torchtext.data import Iterator,BucketIterator

train_iterator=BucketIterator(train_data_csv,
                             batch_size=32,
                             device=-1,
                             sort_key=lambda x:len(x.Body),
                             sort_within_batch=True,
                             repeat=False
                             )

The `device` argument should be set by using `torch.device` or passing a string as an argument. This behavior will be deprecated soon and currently defaults to cpu.


In [191]:
train_data_csv[1].__dict__.keys()

dict_keys(['Title', 'Body', 'Label1Coronovirus', 'Label2Politics', 'Label3Non-Political', 'Label4Objects', 'Label5AskIndia'])

In [58]:
len(TEXT.vocab)

6003

TypeError: 'BucketIterator' object is not subscriptable

In [59]:
for ex in enumerate(train_iterator):
    print(ex)

(0, 
[torchtext.data.batch.Batch of size 32]
	[.Title]:[torch.LongTensor of size 32x18]
	[.Body]:[torch.LongTensor of size 32x94]
	[.Label1Coronovirus]:[torch.LongTensor of size 32]
	[.Label2Politics]:[torch.LongTensor of size 32]
	[.Label3Non-Political]:[torch.LongTensor of size 32]
	[.Label4Objects]:[torch.LongTensor of size 32]
	[.Label5AskIndia]:[torch.LongTensor of size 32])
(1, 
[torchtext.data.batch.Batch of size 32]
	[.Title]:[torch.LongTensor of size 32x16]
	[.Body]:[torch.LongTensor of size 32x0]
	[.Label1Coronovirus]:[torch.LongTensor of size 32]
	[.Label2Politics]:[torch.LongTensor of size 32]
	[.Label3Non-Political]:[torch.LongTensor of size 32]
	[.Label4Objects]:[torch.LongTensor of size 32]
	[.Label5AskIndia]:[torch.LongTensor of size 32])
(2, 
[torchtext.data.batch.Batch of size 32]
	[.Title]:[torch.LongTensor of size 32x22]
	[.Body]:[torch.LongTensor of size 32x233]
	[.Label1Coronovirus]:[torch.LongTensor of size 32]
	[.Label2Politics]:[torch.LongTensor of size 32]
	[.

In [127]:
for example in enumerate(train_iterator):
    #print(example)
    #print(example[1].Label1Coronovirus)
    #print(example[1].Title)
    print(example[1].Body.shape)
    print(example[1].Body)
    break

torch.Size([32, 94])
tensor([[ 212,  940,   34,  ...,  604,  233, 1940],
        [ 524,  350,   98,  ...,  202,  553,    1],
        [4772,  359,  213,  ..., 1002, 2192,    1],
        ...,
        [   2,   63, 1040,  ...,    1,    1,    1],
        [   6,  318,  213,  ...,    1,    1,    1],
        [   6, 2172,  521,  ...,    1,    1,    1]])


In [129]:
example[1].Body.shape

torch.Size([32, 94])

In [130]:
a=torch.zeros((32,1000))
a[:,:example[1].Body.shape[1]]=example[1].Body

In [131]:
a

tensor([[2.1200e+02, 9.4000e+02, 3.4000e+01,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [5.2400e+02, 3.5000e+02, 9.8000e+01,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [4.7720e+03, 3.5900e+02, 2.1300e+02,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [2.0000e+00, 6.3000e+01, 1.0400e+03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [6.0000e+00, 3.1800e+02, 2.1300e+02,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [6.0000e+00, 2.1720e+03, 5.2100e+02,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]])

In [93]:
TEXT.vocab.vectors[100].shape

torch.Size([300])

In [249]:

class BatchWrapper:
    def __init__(self,dat,x_var,*y_vars):
        self.dat=dat
        
        self.x_vars=x_var[0]
        self.y_vars=y_vars
        #self.context=torch.zeros((32,1000))
        self.x_vars2=x_var[1]
        
    def __iter__(self):
        for batch in self.dat:
            x=getattr(batch,self.x_vars)
            batch_siz=x.shape[0]
            
            
            x2=getattr(batch,self.x_vars2)
            #self.context[:batch_siz,:x2.shape[1]]=x2
            y=torch.cat([getattr(batch,y).unsqueeze(1) for y in self.y_vars[0]],dim=1).float()
            
            yield(x,x2,y)

    def __len__(self):
        return len(self.dat)
        
train_dat=BatchWrapper(train_iterator,('Title','Body'),labels)

In [250]:
for x,y in enumerate(train_dat):
    print(x)
    print(y[1])
    print(y[2].shape)
    print(y[0].shape)
    break

0
tensor([[1750,  870, 4410,  ...,  266,  175, 1438],
        [   2,   12, 2643,  ...,    1,    1,    1],
        [1654,   38, 3833,  ...,    1,    1,    1],
        ...,
        [ 520,  611,  429,  ...,    1,    1,    1],
        [4699,    5, 4008,  ...,    1,    1,    1],
        [   2,   92,  244,  ...,    1,    1,    1]])
torch.Size([32, 5])
torch.Size([32, 22])


In [216]:
"""class InputExample(object):
    
    def __init__(self,guid,text_a,labels):
        self.guid=guid
        self.text_a=text_a
        self.labels=labels
"""

'class InputExample(object):\n    \n    def __init__(self,guid,text_a,labels):\n        self.guid=guid\n        self.text_a=text_a\n        self.labels=labels\n'

In [96]:
"""
class InputFeatures(object):
    def __init__(self,
                input_ids,
                input_masks,
                segment_ids,
                label_id,
                is_real_example=True):
        self.input_ids=input_ids
        self.input_masks=input_masks
        self.segment_ids=segment_ids
        self.label_id=label_id
        self.is_real_example=is_real_example
"""

'\nclass InputFeatures(object):\n    def __init__(self,\n                input_ids,\n                input_masks,\n                segment_ids,\n                label_id,\n                is_real_example=True):\n        self.input_ids=input_ids\n        self.input_masks=input_masks\n        self.segment_ids=segment_ids\n        self.label_id=label_id\n        self.is_real_example=is_real_example\n'

In [97]:
"""
class BERTSequenceClassification(PreTrainedBertModel):
    
    def __init__(self,config,num_labels=2):
        super(BERTSequenceClassification,self).__init__(config)
        self.num_labels=num_labels
        self.bert=BertModel(config)
        self.dropout=torch.nn.Dropout(config.hidden_dropout_prob)
        self.classifier=torch.nn.Linear(config.hidden_size,num_labels)
        self.apply(self.init_bert_weights)
        
    def forward(self,input_ids,token_type_ids=None,attention_mask=None,
               labels=None):
        _, pooled_output=self.bert(input_ids,token_type_ids,
                                  attention_mask,output_all_encoded_layers=False)
        

        pooled_output=self.dropout(pooled_output)
        logits=self.classifier(pooled_output)
        
        if labels is not None:
            loss_fct=BCEWithLogitsLoss()
            loss=loss_fct(logits.view(-1,self.num_labels),
                          labels.view(-1,self.num_labels))
            return loss
        else:
            return logits
        

        
    def freeze_bert_encoder(self):
        for param in self.bert.parameters():
            param.requires_grad=False
            
    
    def unfreeze_bert_encoder(self):
        for param in self.bert.parameters():
            param.requires_grad=True
"""

'\nclass BERTSequenceClassification(PreTrainedBertModel):\n    \n    def __init__(self,config,num_labels=2):\n        super(BERTSequenceClassification,self).__init__(config)\n        self.num_labels=num_labels\n        self.bert=BertModel(config)\n        self.dropout=torch.nn.Dropout(config.hidden_dropout_prob)\n        self.classifier=torch.nn.Linear(config.hidden_size,num_labels)\n        self.apply(self.init_bert_weights)\n        \n    def forward(self,input_ids,token_type_ids=None,attention_mask=None,\n               labels=None):\n        _, pooled_output=self.bert(input_ids,token_type_ids,\n                                  attention_mask,output_all_encoded_layers=False)\n        \n\n        pooled_output=self.dropout(pooled_output)\n        logits=self.classifier(pooled_output)\n        \n        if labels is not None:\n            loss_fct=BCEWithLogitsLoss()\n            loss=loss_fct(logits.view(-1,self.num_labels),\n                          labels.view(-1,self.num_labels)

In [62]:
a=list(train_data_csv[0].__dict__.keys())
labels=a[2:]

In [63]:
labels

['Label1Coronovirus',
 'Label2Politics',
 'Label3Non-Political',
 'Label4Objects',
 'Label5AskIndia']

In [65]:
next(train_dat.__iter__())

(tensor([[ 840, 2704, 1408, 2594, 5006,   91, 1030, 1107,   14,    1,    1,    1,
             1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
             1,    1,    1,    1,    1,    1,    1],
         [ 629, 1007,  148,  463, 5158,   47,  524,   14, 4406, 4576,  705, 1200,
          1138,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
             1,    1,    1,    1,    1,    1,    1],
         [3853, 4502,   87,  867, 2534, 1329, 5992, 1152, 4787,    1,    1,    1,
             1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
             1,    1,    1,    1,    1,    1,    1],
         [2238, 3271, 4353, 1208,  698, 4374,    1,    1,    1,    1,    1,    1,
             1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
             1,    1,    1,    1,    1,    1,    1],
         [  21, 2357,  317,  866, 1180,  720,  557,    9,  295,  356, 1476, 1552,
             1,    1,    1,    1,    1,    1,    1

In [66]:
for example in enumerate(train_dat):
    print(example[1][0].shape)
    print(example[1][1])
    print(example[1][2].shape)
    print(example[0])
    break
    
#Here y is much smaller 5 dimensional

torch.Size([32, 17])
tensor([[  89,   23, 1911,  ...,    2, 1228,  113],
        [ 437,   90,    3,  ...,    1,    1,    1],
        [ 437,    8,   83,  ...,    1,    1,    1],
        ...,
        [   7, 1132,  657,  ...,    1,    1,    1],
        [ 145,  145, 1921,  ...,    1,    1,    1],
        [   2,   27,   17,  ...,    1,    1,    1]])
torch.Size([32, 5])
0


In [67]:
pretrained_vecs=TEXT.vocab.vectors

In [391]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable

class Model(nn.Module):
    def __init__(self,n_vocab,
                 pretrained_vec,
                batch_size=16,
                embedding_dim=50,
                hidden_dim=64,
                num_layer=2,
                 dropout=0.3,
                 output_dims=5,
                bidirectional=True):
        super(Model,self).__init__()
        self.n_vocab=n_vocab
        self.batch_size=batch_size
        self.embedding_dim=embedding_dim
        self.hidden_dim=hidden_dim
        self.num_layer=num_layer
        self.bidirectional=bidirectional
        self.dropout=dropout
        
        self.output_dims=output_dims
        
        self.embedding=nn.Embedding(n_vocab,embedding_dim)
        self.embedding.weight.data.copy_(pretrained_vec)
        self.embedding.weight.requires_grad=False
        
        
        self.rnn=nn.LSTM(self.embedding_dim, self.hidden_dim,
                       num_layers=self.num_layer,
                       batch_first=True,bidirectional=self.bidirectional,
                        dropout=0.5)
        
       
        self.fc1=nn.Linear(hidden_dim*2,self.output_dims)
        
        self.dropout=nn.Dropout(dropout)
        self.logsoftmax=nn.LogSoftmax()
    def forward(self,data):
        
            
        embedded=self.embedding(data)
        
        output,(hidden,_)=self.rnn(embedded)
        
        
        #print(f"Hidden Shape {hidden.shape}")
        
        hidden=torch.cat((hidden[-1,:,:],hidden[-2,:,:]),dim=1)
        
        #print(f"Hidden {hidden.shape} Context {context.shape}")
        #hidden=torch.cat((hidden,context),dim=1)
        #print(f"New Hidden Shape {hidden.shape}")
       # print(f"Hidden Dim {hidden.size()}")
        output=self.fc1(hidden)
        output=self.logsoftmax(output)
        
        return output

In [392]:
class fastText(nn.Module):
    def __init__(self,vocab_size,embedding_dim,
                 hidden_size,output_size,pretrained_wv):
        super(fastText,self).__init__()
        self.embedding_dim=embedding_dim
        self.pretrainedwts=pretrained_wv
        self.output_size=output_size
        self.hidden_size=hidden_size
        
        
        
        #Embedding Layer
        self.embedding=nn.Embedding(vocab_size,embedding_dim)
        self.embedding.weight.data.copy_(self.pretrainedwts)
        self.embedding.weight.requires_grad=False
        
        self.fc1=nn.Linear(self.embedding_dim,self.hidden_size)
        
        self.fc2=nn.Linear(self.hidden_size,self.output_size)
        self.softmax=nn.Softmax()

    def forward(self,x):
        embedded=self.embedding(x)
        h=self.fc1(embedded.mean(1))
        z=self.fc2(h)
        return self.softmax(z)

In [393]:
embedding_dim=300
Input_Vocab=len(TEXT.vocab)
model_context=fastText(vocab_size=Input_Vocab,
        embedding_dim=embedding_dim,
        hidden_size=1024,
        output_size=512,
        pretrained_wv=pretrained_vecs)
print(model_context)

fastText(
  (embedding): Embedding(6003, 300)
  (fc1): Linear(in_features=300, out_features=1024, bias=True)
  (fc2): Linear(in_features=1024, out_features=512, bias=True)
  (softmax): Softmax(dim=None)
)


In [394]:
ENC_EMB_DIM=300

HID_DIM=256
ENC_DROPOUT=0.5


Input_Vocab=len(TEXT.vocab)

model=Model(n_vocab=Input_Vocab,pretrained_vec=pretrained_vecs,embedding_dim=ENC_EMB_DIM,hidden_dim=HID_DIM,
           dropout=ENC_DROPOUT)

print(model)

Model(
  (embedding): Embedding(6003, 300)
  (rnn): LSTM(300, 256, num_layers=2, batch_first=True, dropout=0.5, bidirectional=True)
  (fc1): Linear(in_features=512, out_features=5, bias=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (logsoftmax): LogSoftmax()
)


In [395]:
import tqdm
import torch.optim as optim
optimizer=optim.Adam(model.parameters())

#criterion=nn.BCEWithLogitsLoss()
criterion=nn.CrossEntropyLoss()
EPOCH=2

In [383]:
for x,x2,y in tqdm.tqdm(train_dat):
    print(x.shape)
    
    print(y.shape)
    context=model_context(x2)
    print(e.shape)
    pred=model(data=x,context=context)
    print(pred)
    print(f"pred :{torch.max(pred,1)[1]}")
    print(f"y :{torch.max(y,1)[1]}")
    #print(pred.shape)
    #print(np.argmax(y))
    loss=criterion(pred,torch.max(y,1)[1])
    print(loss)
    
    break
    

a=pred.squeeze(0)
b=y

  0%|          | 0/15 [00:00<?, ?it/s]/home/ishan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:26: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
/home/ishan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:59: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  0%|          | 0/15 [00:00<?, ?it/s]

torch.Size([32, 22])
torch.Size([32, 5])
torch.Size([32, 512])
tensor([[-1.6211, -1.6052, -1.5963, -1.6253, -1.5997],
        [-1.6222, -1.6084, -1.5918, -1.6213, -1.6038],
        [-1.6251, -1.6083, -1.5970, -1.6181, -1.5991],
        [-1.6215, -1.6051, -1.5948, -1.6191, -1.6069],
        [-1.6246, -1.6060, -1.5967, -1.6233, -1.5971],
        [-1.6233, -1.6157, -1.5866, -1.6270, -1.5952],
        [-1.6197, -1.5989, -1.5987, -1.6258, -1.6043],
        [-1.6220, -1.6077, -1.5982, -1.6192, -1.6003],
        [-1.6165, -1.6058, -1.6001, -1.6274, -1.5977],
        [-1.6214, -1.6023, -1.5938, -1.6248, -1.6052],
        [-1.6233, -1.6049, -1.5949, -1.6258, -1.5987],
        [-1.6160, -1.6081, -1.5918, -1.6274, -1.6042],
        [-1.6190, -1.6071, -1.5958, -1.6194, -1.6062],
        [-1.6183, -1.6085, -1.5949, -1.6247, -1.6012],
        [-1.6209, -1.6088, -1.5926, -1.6217, -1.6034],
        [-1.6173, -1.6120, -1.5913, -1.6309, -1.5963],
        [-1.6178, -1.6034, -1.6001, -1.6191, -1.6070],
  

In [365]:
print(x.shape,x2.shape)

a=torch.cat((x,x2),dim=1)
a.shape

torch.Size([25, 33]) torch.Size([25, 1482])


torch.Size([25, 1515])

In [396]:
epoch_loss_dat=[]

In [402]:
def train(model,train_iter):
    for epoch in range(1,20):
        running_loss=0.0
        running_corrects=0
        model.train()
        epoch_lo=0
        for x,x2,y in tqdm.tqdm(train_iter):
            optimizer.zero_grad()
            #print(x)
            
            preds=model(data=x)
            
            #print(f"y: {preds.shape}")
            preds=preds.squeeze(0)
            
            #print(f"Preds {preds}")
            loss=criterion(preds,torch.max(y,1)[1])
            
            epoch_lo+=(torch.max(preds,1)[1]==torch.max(y,1)[1]).sum()
            
            #print(f"Hello {preds.shape}, {y.shape}")
            """for i in range(len(preds)):
                k=preds[i].detach().numpy()
                print(np.argmax(k))
                d=y[i].detach().numpy()
                if(np.argmax(k)==np.argmax(d)):
                    #print(np.argmax(k))
                    epoch_lo+=1
            """
            #print(preds)
            #print(preds.shape)
            
            #loss=criterion(y,preds)
            loss.backward()
            optimizer.step()
            
            running_loss+=loss.item()*x.size(0)
        epoch_loss=running_loss/473
        epoch_loss_dat.append(epoch_loss)
        print(f'Epoch :{epoch}, Training Loss: {epoch_loss}, Num_Correct={epoch_lo}')

In [403]:
train(model,train_dat)

  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :1, Training Loss: 0.3298380454297298, Num_Correct=418


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :2, Training Loss: 0.29333365858231236, Num_Correct=425


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :3, Training Loss: 0.2502354103717441, Num_Correct=426


  7%|▋         | 1/15 [00:00<00:02,  5.50it/s]

Epoch :4, Training Loss: 0.2423544897369048, Num_Correct=430


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :5, Training Loss: 0.2257117460507419, Num_Correct=438


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :6, Training Loss: 0.12707541312778223, Num_Correct=450


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :7, Training Loss: 0.19555748680933333, Num_Correct=444


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :8, Training Loss: 0.1521158265324022, Num_Correct=450


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :9, Training Loss: 0.17401565842913272, Num_Correct=444


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :10, Training Loss: 0.12069068880590274, Num_Correct=449


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :11, Training Loss: 0.08895715228803693, Num_Correct=459


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :12, Training Loss: 0.05278821067833371, Num_Correct=465


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :13, Training Loss: 0.040540807642215904, Num_Correct=466


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :14, Training Loss: 0.03699585441184913, Num_Correct=468


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :15, Training Loss: 0.033835598705710554, Num_Correct=467


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :16, Training Loss: 0.02157534396839003, Num_Correct=468


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :17, Training Loss: 0.01851617016221139, Num_Correct=468


  0%|          | 0/15 [00:00<?, ?it/s]

Epoch :18, Training Loss: 0.020474647829431182, Num_Correct=468


100%|██████████| 15/15 [00:05<00:00,  2.65it/s]

Epoch :19, Training Loss: 0.019376098095630366, Num_Correct=468


In [ ]:
##Stop Words removing was good

In [ ]:
#CrossEntropy Loss -Final-Very Nice 1.1742

In [328]:
a=torch.rand((1,10))
a[0]=0
a

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [329]:
b=torch.zeros((1,10))
b

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [330]:
(a==b).sum()

tensor(10)